package practiceRandom;

public class RandomPracticeEx2 {

	public static void main(String[] args) {
		RandomPracticeEx2 te = new RandomPracticeEx2();
		try {
			te.test(0);
		} catch (ArithmeticException e) {
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void test(int x) throws Exception{
		if (x == 0) {
			throw new ArithmeticException("我認為0是錯誤！！！");
		}
	}
}
